services:
  db:
    image: postgres:15
    container_name: duylongtech_db
    environment:
      POSTGRES_DB: duylongtech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: ../docker-setup/backend.Dockerfile
    container_name: duylongtech_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/duylongtech
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
    volumes:
      - ../backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker-setup/frontend.Dockerfile
    container_name: duylongtech_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
